// prisma/seed.ts
import { PrismaClient, Role } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // Seed admin (update password too so re-seed resets to admin123)
  const adminPassword = await bcrypt.hash('admin123', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@threadhaus.com' },
    update: { password: adminPassword, role: Role.ADMIN, name: 'Super Admin' },
    create: {
      name: 'Super Admin',
      email: 'admin@threadhaus.com',
      password: adminPassword,
      role: Role.ADMIN,
    },
  });

  // Seed editor (update password too so re-seed resets to editor123)
  const editorPassword = await bcrypt.hash('editor123', 12);
  const editor = await prisma.user.upsert({
    where: { email: 'editor@threadhaus.com' },
    update: { password: editorPassword, role: Role.EDITOR, name: 'Content Editor' },
    create: {
      name: 'Content Editor',
      email: 'editor@threadhaus.com',
      password: editorPassword,
      role: Role.EDITOR,
    },
  });

  // Seed site settings
  await prisma.siteSettings.upsert({
    where: { id: 'default' },
    update: {},
    create: {
      id: 'default',
      bannerTitle: 'Thread Haus',
      bannerSubtitle: 'Premium T-Shirts Crafted for the Bold',
      featuredSection: 'Featured Collection',
    },
  });

  // Seed products (upsert by title to avoid duplicates on re-run)
  const products = [
    {
      title: 'Phantom Black Crew',
      description: 'Ultra-soft 100% organic cotton. A staple redefined with heavyweight 280gsm fabric that drapes perfectly.',
      price: 1299,
      comparePrice: 1599,
      image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
      images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Slim Fit', 'Cropped'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#000000', '#1a1a2e', '#16213e'],
      stock: 50,
      isFeatured: true,
      tags: ['black', 'crew', 'basic'],
      createdById: admin.id,
    },
    {
      title: 'Arctic White Essential',
      description: 'Pure white minimalism at its finest. Triple-washed for ultimate softness.',
      price: 1199,
      comparePrice: 1499,
      image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Boxy'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#ffffff', '#f5f5f0', '#e8e8e0'],
      stock: 75,
      isFeatured: true,
      tags: ['white', 'essential', 'minimal'],
      createdById: admin.id,
    },
    {
      title: 'Terracotta Sunset Tee',
      description: 'Earthy tones for the modern soul. Garment-dyed for a lived-in look from day one.',
      price: 1399,
      image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800',
      images: ['https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Relaxed'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#c1440e', '#d4691e', '#8b2500'],
      stock: 30,
      isFeatured: true,
      tags: ['terracotta', 'earthy', 'premium'],
      createdById: editor.id,
    },
    {
      title: 'Sage Green Everyday',
      description: 'Muted greens for a calm, collected look. French terry interior for warmth.',
      price: 1499,
      image: 'https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800',
      images: ['https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Cropped'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['#87a878', '#6b8f61', '#4a7c59'],
      stock: 40,
      isFeatured: false,
      tags: ['sage', 'green', 'everyday'],
      createdById: admin.id,
    },
    {
      title: 'Midnight Navy Classic',
      description: 'The navy tee done right. Structured shoulders, relaxed body.',
      price: 1299,
      image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
      images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800'],
      availableCuts: ['Regular', 'Slim Fit', 'Athletic'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#0a0a2e', '#1a1a5e', '#161676'],
      stock: 60,
      isFeatured: false,
      tags: ['navy', 'classic', 'structured'],
      createdById: editor.id,
    },
    {
      title: 'Dust Rose Vintage Wash',
      description: 'Soft rose hues with a vintage garment wash. Perfect for any occasion.',
      price: 1349,
      comparePrice: 1599,
      image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800',
      images: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Boxy', 'Cropped'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['#d4a0a7', '#c47f8a', '#b06070'],
      stock: 25,
      isFeatured: true,
      tags: ['rose', 'vintage', 'feminine'],
      createdById: admin.id,
    },
    {
      title: 'Charcoal Heather Staple',
      description: 'Heathered grey for everyday comfort. Goes with everything.',
      price: 1199,
      image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800',
      images: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Slim Fit'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#4a4a4a', '#6b6b6b', '#2d2d2d'],
      stock: 55,
      isFeatured: false,
      tags: ['charcoal', 'heather', 'staple'],
      createdById: admin.id,
    },
    {
      title: 'Ocean Blue Relaxed Fit',
      description: 'Cool blue tones for a fresh, casual look. Breathable cotton.',
      price: 1349,
      comparePrice: 1699,
      image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800',
      images: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Relaxed'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#2563eb', '#1d4ed8', '#3b82f6'],
      stock: 45,
      isFeatured: false,
      tags: ['blue', 'ocean', 'relaxed'],
      createdById: editor.id,
    },
    {
      title: 'Mustard Gold Statement',
      description: 'Bold mustard for the trend-setter. Stand out from the crowd.',
      price: 1449,
      image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800',
      images: ['https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Boxy'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['#eab308', '#ca8a04', '#a16207'],
      stock: 35,
      isFeatured: false,
      tags: ['mustard', 'gold', 'bold'],
      createdById: admin.id,
    },
    {
      title: 'Cement Grey Minimal',
      description: 'Light grey minimalist tee. Clean lines, premium feel.',
      price: 1249,
      image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
      images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800'],
      availableCuts: ['Regular', 'Slim Fit', 'Athletic'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#9ca3af', '#6b7280', '#4b5563'],
      stock: 60,
      isFeatured: false,
      tags: ['cement', 'grey', 'minimal'],
      createdById: editor.id,
    },
    {
      title: 'Burgundy Wine Classic',
      description: 'Rich burgundy for a sophisticated look. Perfect for layering.',
      price: 1399,
      comparePrice: 1699,
      image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Relaxed'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#722f37', '#8b3a42', '#5c252b'],
      stock: 40,
      isFeatured: true,
      tags: ['burgundy', 'wine', 'classic'],
      createdById: admin.id,
    },
    {
      title: 'Olive Green Utility',
      description: 'Military-inspired olive. Durable and versatile.',
      price: 1299,
      image: 'https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800',
      images: ['https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Boxy'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#556b2f', '#6b8e23', '#3d5c1f'],
      stock: 50,
      isFeatured: false,
      tags: ['olive', 'utility', 'military'],
      createdById: editor.id,
    },
    {
      title: 'Coral Summer Vibes',
      description: 'Bright coral for warm days. Lightweight and breezy.',
      price: 1199,
      image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800',
      images: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800'],
      availableCuts: ['Regular', 'Cropped', 'Slim Fit'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['#ff7f7f', '#e57373', '#ef5350'],
      stock: 38,
      isFeatured: false,
      tags: ['coral', 'summer', 'bright'],
      createdById: admin.id,
    },
    {
      title: 'Steel Blue Workhorse',
      description: 'Reliable steel blue. Your go-to for any occasion.',
      price: 1149,
      image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
      images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800'],
      availableCuts: ['Regular', 'Slim Fit', 'Athletic'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#4682b4', '#5c9fd4', '#2e5a7b'],
      stock: 70,
      isFeatured: false,
      tags: ['steel', 'blue', 'workhorse'],
      createdById: editor.id,
    },
    {
      title: 'Sand Beige Neutral',
      description: 'Warm sand tones. Timeless and understated.',
      price: 1249,
      image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800',
      images: ['https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Relaxed'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#c2b280', '#d4c99b', '#a89868'],
      stock: 42,
      isFeatured: false,
      tags: ['sand', 'beige', 'neutral'],
      createdById: admin.id,
    },
    {
      title: 'Lavender Dream Soft',
      description: 'Soft lavender for a dreamy aesthetic. Comfort first.',
      price: 1349,
      image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Cropped'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['#e6e6fa', '#d8bfd8', '#9370db'],
      stock: 33,
      isFeatured: false,
      tags: ['lavender', 'dream', 'soft'],
      createdById: editor.id,
    },
    {
      title: 'Moss Green Earth',
      description: 'Deep moss green. Connects you to nature.',
      price: 1299,
      image: 'https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800',
      images: ['https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800'],
      availableCuts: ['Regular', 'Boxy', 'Oversized'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#2d5a27', '#3d7a35', '#1e4a1a'],
      stock: 48,
      isFeatured: false,
      tags: ['moss', 'green', 'earth'],
      createdById: admin.id,
    },
    {
      title: 'Rust Autumn Tee',
      description: 'Warm rust for autumn vibes. Cozy and stylish.',
      price: 1399,
      comparePrice: 1699,
      image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
      images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Relaxed'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['#b7410e', '#cd5c2a', '#8b2e0a'],
      stock: 28,
      isFeatured: true,
      tags: ['rust', 'autumn', 'warm'],
      createdById: editor.id,
    },
    {
      title: 'Slate Grey Professional',
      description: 'Polished slate for a professional edge. Office to weekend.',
      price: 1279,
      image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800',
      images: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800'],
      availableCuts: ['Regular', 'Slim Fit', 'Athletic'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#708090', '#4a5568', '#2d3748'],
      stock: 52,
      isFeatured: false,
      tags: ['slate', 'professional', 'polished'],
      createdById: admin.id,
    },
    {
      title: 'Peach Blush Soft',
      description: 'Delicate peach blush. Feminine and fresh.',
      price: 1199,
      image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800',
      images: ['https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800'],
      availableCuts: ['Regular', 'Cropped', 'Slim Fit'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['#ffcba4', '#ffb088', '#ff9a6c'],
      stock: 36,
      isFeatured: false,
      tags: ['peach', 'blush', 'soft'],
      createdById: editor.id,
    },
    {
      title: 'Ink Black Premium',
      description: 'Deepest black. Premium 280gsm construction.',
      price: 1499,
      comparePrice: 1899,
      image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
      images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Slim Fit', 'Boxy', 'Athletic'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#0d0d0d', '#1a1a1a', '#000000'],
      stock: 80,
      isFeatured: true,
      tags: ['black', 'ink', 'premium'],
      createdById: admin.id,
    },
    {
      title: 'Ivory Cream Luxe',
      description: 'Creamy ivory for an elevated look. Ultra-soft hand feel.',
      price: 1349,
      image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Relaxed'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#fffef5', '#f5f5dc', '#fff8dc'],
      stock: 44,
      isFeatured: false,
      tags: ['ivory', 'cream', 'luxe'],
      createdById: editor.id,
    },
    {
      title: 'Forest Green Heritage',
      description: 'Classic forest green. Heritage quality, modern fit.',
      price: 1299,
      image: 'https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800',
      images: ['https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Slim Fit'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#228b22', '#2e8b2e', '#1a5f1a'],
      stock: 58,
      isFeatured: false,
      tags: ['forest', 'green', 'heritage'],
      createdById: editor.id,
    },
    {
      title: 'Maroon Deep Classic',
      description: 'Rich maroon. A wardrobe essential.',
      price: 1249,
      image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
      images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Boxy'],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['#800020', '#722f37', '#5c1825'],
      stock: 41,
      isFeatured: false,
      tags: ['maroon', 'deep', 'classic'],
      createdById: editor.id,
    },
    {
      title: 'Sky Blue Fresh',
      description: 'Light sky blue for a breath of fresh air. Perfect for summer.',
      price: 1149,
      image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800',
      images: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800'],
      availableCuts: ['Regular', 'Oversized', 'Cropped'],
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: ['#87ceeb', '#b0e0e6', '#5dade2'],
      stock: 62,
      isFeatured: false,
      tags: ['sky', 'blue', 'fresh'],
      createdById: admin.id,
    },
  ];

  for (const product of products) {
    const existing = await prisma.product.findFirst({
      where: { title: product.title },
    });
    if (!existing) {
      await prisma.product.create({
        data: { ...product, isActive: true },
      });
    }
  }

  const count = await prisma.product.count({ where: { isActive: true } });
  console.log(`✅ Database seeded successfully (${count} active products)`);
  console.log('Admin: admin@threadhaus.com / admin123');
  console.log('Editor: editor@threadhaus.com / editor123');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
